name: Deploy to cPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull from remote on cPanel
        run: |
          curl -s \
            -H "Authorization: cpanel studpeki:${{ secrets.CPANEL_API_TOKEN }}" \
            "https://premium88.web-hosting.com:2083/execute/VersionControl/update" \
            --data-urlencode "repository_root=/home/studpeki/mauriportfolio"
      - name: Deploy HEAD commit
        run: |
          curl -s \
            -H "Authorization: cpanel studpeki:${{ secrets.CPANEL_API_TOKEN }}" \
            "https://premium88.web-hosting.com:2083/execute/VersionControlDeployment/create" \
            --data-urlencode "repository_root=/home/studpeki/mauriportfolio"
